"""lighting

Revision ID: 0a06d8b82b4f
Revises: 7ca004e41464
Create Date: 2022-08-16 18:03:02.399037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a06d8b82b4f'
down_revision = '7ca004e41464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lighting',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('UUID', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('lighting_type', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['lighting_type'], ['lighting_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lighting_id'), 'lighting', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lighting_id'), table_name='lighting')
    op.drop_table('lighting')
    # ### end Alembic commands ###
