"""Second

Revision ID: f1008759c6f2
Revises: 4fb49eb5f098
Create Date: 2022-08-16 13:52:35.659376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1008759c6f2'
down_revision = '4fb49eb5f098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lighting_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('UUID', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('watt', sa.Integer(), nullable=True),
    sa.Column('connection_type', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', 'UUID')
    )
    op.create_index(op.f('ix_lighting_type_id'), 'lighting_type', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lighting_type_id'), table_name='lighting_type')
    op.drop_table('lighting_type')
    # ### end Alembic commands ###
